[tool.poetry]
name = "hpi-chatbot-frontend"
version = "0.1.0"
description = "frontend for heatpump installer chatbot"
authors = ["sqr00t <797346+sqr00t@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10, <3.13"
streamlit = "^1.45.1"
langserve = {extras = ["client"], version = "0.3.1"}
langfuse = "^2.60.5"
streamlit-feedback = "^0.1.4"
streamlit-extras = "^0.7.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
